=== adam-stack-vc/606_app/results/analysis_output2/conversion_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "filename": {
      "type": "string"
    },
    "url": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "date": {
      "type": "string"
    },
    "sentiment": {
      "type": "string"
    },
    "text": {
      "type": "string"
    },
    "text_length": {
      "type": "integer"
    },
    "source": {
      "type": "string"
    },
    "processing_info": {
      "type": "object",
      "properties": {
        "converted_at": {
          "type": "string"
        },
        "source_file": {
          "type": "string"
        }
      },
      "required": [
        "converted_at",
        "source_file"
      ]
    }
  },
  "required": [
    "filename",
    "url",
    "text",
    "source",
    "processing_info"
  ]
}

=== adam-stack-vc/606_app/results/json_output/row_027_thecoin_news_extracted.json
{
  "filename": "row_027_thecoin_news_extracted",
  "url": "https://thecoin.news/articles/robinhoods-shrinking-reliance-payment-order-flow-reflects-growing-role-crypto-revenue-1628020113075",
  "title": "Robinhood's shrinking reliance on payment for order flow reflects the growing role of crypto revenue",
  "date": "2/6/23",
  "sentiment": "Neutral",
  "text": "----------------------------------------\nWhat can I do?\nIf you're a visitor of this website:\nPlease try again in a few minutes.\nIf you're the owner of this website:\nContact your hosting provider letting them know your web server is not completing requests. An Error 522 means that the request was able to connect to your web server, but that the request didn't finish. The most likely cause is that something on your server is hogging resources. Additional troubleshooting information here.",
  "text_length": 490,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.471122",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_027_thecoin_news_extracted.txt"
  }
}

=== adam-stack-vc/606_app/results/json_output/row_065_tokenist_com_extracted.json
{
  "filename": "row_065_tokenist_com_extracted",
  "url": "https://tokenist.com/robinhood-owes-citadel-43-of-its-q1-2021-revenue",
  "title": "43% of Robinhood’s Q1 2021 Revenue is from Citadel",
  "date": "5/5/21",
  "sentiment": "Negative, Neutral",
  "text": "----------------------------------------\nEditorial note: The title of this article was updated on May 5th, 2021, to provide further clarification on Robinhood’s source of revenue. The previous title may have been confusing.\nAs one delves deeper into the underpinnings of high finance, it is becoming more clear that a ‘true’ free market has difficulty existing outside of decentralized finance. Although the Robinhood-Citadel relationship sheds light on little-known dealings, these two particular entities are merely placeholders for a system that works, well, the only way it can work.\nMany have wondered what the financial outcome of WallStreetBets’ GameStop trading for Robinhood is—the brokerage that can be thanked for introducing zero-commission trading. No matter Robinhood’s subsequent reputation, it is safe to say it changed the stock market landscape, forcing all other brokerages to follow. Now that Robinhood Securities filed an SEC earnings report for Q1 2021, we can see that Robinhood’s revenue increased by 263% when compared to Q1 2020.\nMore importantly, we can visualize Robinhood’s relationship with Citadel Securities market maker, to whom it sold market order flows among four other market makers: Virtu Americas, Two Sigma Securities, G1X Execution Services, and Wolverine Securities.\nOverall, out of the $331 million pie for Q1 2021, Robinhood generated $133 million from stock trading and $198 million from options trading. As Robinhood is scheduled to be listed on Nasdaq in the first half of 2021, it will be interesting to see its stock performance given these revelations and remaining unresolved lawsuits.\nIn the same Q1 2021 period, Melvin Capital – a hedge fund – lost about half of its total capital during the GME action as it tried to short sell the gaming retail chain. It then came to light that Citadel Securities, Robinhood’s core income source for order flows, also had a large stake in Melvin Capital. Conspicuously, at the height of GME’s short squeeze, Robinhood restricted the trading of GME and a number of other affected stocks.\nMore conspicuously, it has been revealed that Citadel Securities has a rich history of collecting FINRA/SEC violations. In the meantime, its conglomerate serves as both an exchange and a market maker. Last year, Citadel captured just over 13% of all trading volume in the US. For GME trading specifically, Robinhood supplied the market maker with up to 40% of trading volume, including both options and stocks.\nYou see, a brokerage like Robinhood has no choice but to route its order flows to market makers. After all, Robinhood is merely an intermediary for the trader. It is MMs that facilitate the orders by infusing the market with liquidity. For this task, they have to be large financial institutions like Citadel, in order to cover for a large volume of ask and bid positions.\nBy actively participating on the both sides of the market, MMs not only pay for order flows (PFOF), but they also charge for ask and bid spreads to cover for the risk of holding securities that may devalue after the purchase. Of course, by doing this, they also detect trading patterns unavailable to retail traders.\nAs you can tell, that’s a lot of faith to be placed in a system ridden with vested, conflicting interests. Various lawsuits and violations may come and go, but the system will remain as it is— in large part, because it is centralized. In this light, following the emergence of blockchain and smart contracts, a project like Uniswap could be considered a more significant pioneer than Robinhood.\nThe DeFi protocol introduced automated market makers (AMMs) consisting of liquidity pools and liquidity providers, thus creating a decentralized exchange (DEX). Currently pooling $7.5 billion, Uniswap rewards liquidity providers for locking in their crypto assets. These rewards are commonly called yield farming.\nThere are no brokerages and market-making behemoths looking to put a spike in certain trades. Everything is automated and decentralized. Just today, on May 5th, Uniswap is set to launch a massive v3 upgrade on the Ethereum mainnet, introducing a number of improvements that give yield-farmers greater control to customize their gains and increase their capital efficiency.\nGiven the way Ethereum has been outperforming Bitcoin in anticipation of its proof-of-stake (PoS) transition, this may be the time to consider which kind of finance instills more confidence: One that is highly susceptible to the corruptibility of human minds, or one that relies on an open-source, blockchain-fortified code of ones and zeros?\nHave you looked into Ethereum network’s staking or DeFi protocols since GME trading? Let us know in the comments below.",
  "text_length": 4721,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.511173",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_065_tokenist_com_extracted.txt"
  }
}

=== adam-stack-vc/606_app/results/json_output/row_224_ft_com_extracted.json
{
  "filename": "row_224_ft_com_extracted",
  "url": "https://ft.com/content/696a15e0-64f1-4800-af79-4d0a882df5b2",
  "title": "SEC needs to find a way to curb payment for order flow",
  "date": "",
  "sentiment": "Negative",
  "text": "----------------------------------------\nThe writer is a former chair of the US Federal Deposit Insurance Corporation\nSecurities and Exchange Commission chair Gary Gensler has cast a long-needed spotlight on the practice of brokers selling their retail orders to makers of markets outside of regulated, public exchanges.\nTypically, these are “dark pools” — private exchanges run by large financial institutions — or “wholesalers” such as Citadel Securities and Virtu that execute orders internally.\nCritics say payment for order flow, or PFOF, represents an inherent conflict of interest, sensibly observing that brokers should be routing orders where they can get the best price for their customers, not the best deal for themselves.\nSupporters argue that PFOF benefits retail investors, as market makers are required to provide prices that are better than quotes displayed by regulated exchanges. They add that broker profits from PFOF allow them to offer commission-free trading.\nBut it is far from clear whether PFOF actually reduces costs for retail investors, or simply makes their costs less transparent. By allowing market makers to attract order flow with a lawful bribe, not a best price, PFOF gives them every incentive to hide the true price at which they are willing to trade, probably leading to poorer executions for retail traders.\nUnlike market makers on public exchanges, dark pools and wholesalers are not required to publish and stand behind quotes. When they pay for an order, they have the discretion to trade against it or send it to an exchange.\nWhile exchange market makers must improve a published price by a penny, there is no such requirement for dark pools and wholesalers, which can and do “improve” price by tiny fractions of a cent.\nThus, PFOF affords them the luxury of not having to compete on price to draw order flow, and to step in front of those who do, with minimal price improvement.\nThis reduces competition, but also creates disincentives for others to publicly expose their trading interest, knowing dark pools and wholesalers can so easily — and cheaply — jump ahead of them.\nThe relationship of PFOF to pricing quality was vividly illustrated in a recent enforcement settlement brought by the SEC against Robinhood. In that case, Robinhood explicitly agreed to accept less price improvement for its customers in return for a higher PFOF. The inferior executions given to those Robinhood customers may well have exceeded any benefit from not paying a commission.\nLong ago, the UK’s Financial Services Authority wisely recognised the harm of PFOF to market quality and integrity, in effect banning it in 2012. A study conducted by the CFA Institute of UK markets found that absent PFOF, markets were more liquid and pricing improved for retail investors.\nThe reason is simple: when market makers have to compete on the quality of their public quotes and are rewarded with trades at those quotes, they compete more aggressively. Incentives are aligned.\nIronically, Bernard Madoff of Ponzi scheme fame, pioneered the use of PFOF in the 1980s, arguing to the SEC that it would increase competition for exchanges, then dominated by the NYSE. Exchange market share has indeed shrunk to barely half, but concentrations have accumulated off-exchange.\nWholesalers now account for 38 per cent of US trading volumes, mostly dominated by seven firms. Market share for retail orders is even more concentrated, with Citadel accounting for 47 per cent. This market dominance brings tremendous advantages for Citadel, including a privileged first look at retail order flow — a force that increasingly moves share prices, as we have seen recently with GameStop and other meme stocks.\nGensler has said a number of market structure reforms are on the table, including banning PFOF. That may be difficult, as many “free” brokers might start charging commissions again to make up for lost revenue. This would be unpopular with retail investors who also vote and make political donations. However, the return of commissions is not a foregone conclusion. Brokers such as Fidelity are able to offer commission-free trades without resorting to PFOF.\nPFOF serves as another reminder to all regulators to scrutinise schemes purportedly benefiting the little guy. History is replete with them. Madoff will be forever remembered for his multibillion-dollar Ponzi scheme, but his more impactful legacy may be the damage to investors from PFOF. Let’s hope the SEC can find a way to make things right.\nThis article has been revised since original publication to make clearer that the inducement that PFOF entails is lawful. The article also has been amended to include an entity’s full name, Citadel Securities.",
  "text_length": 4723,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.515072",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_224_ft_com_extracted.txt"
  }
}

=== adam-stack-vc/606_app/results/json_output/row_109_cantor_com_extracted.json
{
  "filename": "row_109_cantor_com_extracted",
  "url": "https://cantor.com/sec-rule-606-order-disclosure",
  "title": "SEC Rule 606 Order Disclosure - Cantor",
  "date": "",
  "sentiment": "Neutral",
  "text": "----------------------------------------\nThe U.S. Securities and Exchange’s Rule 606 (“Rule 606”) requires broker-dealers, such as Cantor Fitzgerald (“CF&Co.”) that route customer orders in equity and option securities, to make publicly available quarterly reports that, among other things, identify the market centers to which customer orders are routed for execution.\nSection (a)(1) of Rule 606 provides information on the routing of “non-directed orders” â€” any order that the customers has not specifically instructed to be routed to a particular venue or market center for execution. The Rule 606 Report (the “Report”) presents the order routing information by calendar month and is divided into three sections:\n– Section 1 – National Market System (“NMS”) stock orders in securities included in the S&P 500 Index;\n– Section 2 – NMS stock orders in securities that are not included in the S&P 500 Index; and\nEach section of the Report includes information concerning certain market centers to which CF&Co. has routed orders, sets forth the percentage of various types of non-directed orders routed to these market centers (e.g., market, marketable limit, non-marketable limit, other), and discusses the material aspects of CF&Co.’s relationship with these market centers. Material aspects of the relationship include a description of the terms of any payment for order flow and any profit-sharing arrangements that may influence a broker-dealer’s order routing decision.\nSection (b)(1) of SEC Rule 606 requires CF&Co. to disclose to its customers, upon request, for held orders in NMS stocks and orders in NMS securities that are option contracts, the identity of the venue to which the customer’s orders were routed for execution in the six months prior to the request, whether the orders were directed orders or non-directed orders, and the time of the transactions, if any, that resulted from such orders\nIn addition, the Firm shall, pursuant to Rule 606(b)(3) provide customers upon request, an individualized report concerning how CF&Co. handed that customer’s not held orders in NMS stocks for the prior six months. This report will be divided into separate sections for a customer’s directed orders and non-directed orders, in conformance with the “XML schema” published on the SEC website and is required to be produced within seven business days of the customer’s request. Clients may request a report generated pursuant to SEC Rule 606(b)(3) by contacting CF&Co.\nDASH and WEX route CF&Co. option orders to various Options Exchanges as CF&Co. orders are not exposed to either WEX or Dash’s execution/market making affiliates/entities. As a result of this workflow, DASH and WEX are not considered “consolidators” (as orders are not sent to them “for execution”), thus CF&Co. denotes the downstream venues on the SEC Rule 606(a)(1) report.\nCF&Co. receives and handles all option orders on a “Not Held” basis.Â CF&Co. does not base options order routing decisions on the receipt of payment for order flow or any other order routing inducements. CF&Co. effectively manages this potential conflict of interest by adhering to CF&CO. ’s duty to achieve best execution. In addition, CF&CO. provides customer disclosures regarding its payment for order flow practices, and makes order routing determinations wholly independently from any rebates or similar payments that CF&Co. may receive. For further information regarding CF&CO. ’s best execution practices, please see CF&CO. ’s disclosuresÂ which can be found here https://www.cantor.com/disclosures/\nCF&Co. does not have in place any incentives for equaling or exceeding an agreed upon order flow volume threshold, such as additional payments or a higher rate of payment; nor does CF&CO. have in place any disincentives for failing to meet an agreed upon minimum order flow threshold, such as lower payments or the requirement to pay a fee. CF&CO. does not have in place a volume-based tiered payment schedules; nor does CF&CO. have any agreements in place regarding the minimum amount of order flow that the CF&CO. will send to a venue. In addition CF&Co does not participate in a profit sharing type of relationship with WEX or DASH.",
  "text_length": 4197,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.516210",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_109_cantor_com_extracted.txt"
  }
}

=== adam-stack-vc/606_app/results/json_output/row_005_dailyforex_com_extracted.json
{
  "filename": "row_005_dailyforex_com_extracted",
  "url": "https://dailyforex.com/comparison/robinhood-vs-etrade",
  "title": "Robinhood vs E*TRADE - Which is better, Robinhood or E*TRADE? Updated 2025",
  "date": "5/4/25",
  "sentiment": "Neutral",
  "text": "----------------------------------------\nRobinhood and E*TRADE are well-known equity brokers, but which one should you trust for your investment portfolios?\nI have conducted an in-depth review of Robinhood vs. E*TRADE to determine which broker is the better overall choice and which traders will benefit most from each.\nHere is a snapshot of the most notable advantages of Robinhood:\n• Share dealing from $1 with an on-ramp for cryptocurrency traders on its mobile app\n• A stainless-steel, branded Visa debit card with 3% cashback on all transactions\nHere is a snapshot of the most notable advantages of E*TRADE:\n• The cutting-edge Power E*TRADE trading platform for active traders, including technical pattern recognition, the Earnings Move Analyzer, and risk/reward probabilities\nBoth brokers offer fractional share investments, stocks, IPOs, ETFs, options, futures, and managed robo-advisories. Robinhood includes gold and select cryptocurrencies, while E*TRADE features mutual funds and bonds.\nHere is why E*TRADE is a better choice for most traders:\nRobinhood and E*TRADE offer commission-free accounts, but which is cheaper?\nRobinhood and E*TRADE provide commission-free equity and ETF trading. The former does not charge contract fees for options and futures trading, while the latter features volume-based options discounts. Therefore, the determination of which option is cheaper depends on the assets, as both brokers offer their own advantages.\nRobinhood has a Gold account for a $5 monthly fee that offers superior trading conditions. Meanwhile E*TRADE lists 18 account types.\nAre there any other noteworthy differences in the account structure between Robinhood and E*TRADE?\nHere is what stands out the most:\n• E*TRADE managed accounts are available under its Core Portfolios service, which requires a minimum deposit of $500\nHow Difficult Is It to Deposit at Robinhood vs. E*TRADE?\nWhile neither broker has a trader-friendly deposit infrastructure, depositing at Robinhood and E*TRADE is as simple as online banking. Robinhood and E*TRADE rely on bank-related payment processors, but Robinhood presents its branded Visa debit card with 3% cashback on all transactions, granting it an edge. Neither broker has a minimum deposit, but select services carry minimums.\nWhich Withdrawal Process Is Better: Robinhood or E*TRADE?\nNeither Robinhood nor E*TRADE has a quality withdrawal process. Robinhood charges a withdrawal fee for withdrawals to external credit/debit cards and bank accounts and favors traders using its branded Visa debit card. E*TRADE prefers clients use banking services provided by its corporate owner, Morgan Stanley. Among bank-related options, ACH transfers are free and the fastest method.\nWhich Broker Is More Secure and Trustworthy?\nRobinhood is one of the pioneers of commission-free trading in the US but has a questionable operational track record, and supplements income with payment for order flow. Morgan Stanley, the corporate owner of E*TRADE, is publicly listed and a well-recognized bank. Both Robinhood and E*TRADE segregate client deposits from corporate funds and are FINRA members, but overall, E*TRADE is more trustworthy.\nWhich Forex Broker Is Better?\nRobinhood and E*TRADE are well-known equity and ETF brokers, and I recommend traders evaluate their products and services to determine which suits their requirements.\nMy analysis has shown that Robinhood offers fractional shares ideal for smaller portfolios but has a controversial track record. The Morgan Stanley acquisition has added banking services and elevated E*TRADE to a prime broker for US clients with excellent price improvement technology.",
  "text_length": 3655,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.516558",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_005_dailyforex_com_extracted.txt"
  }
}

=== adam-stack-vc/606_app/results/json_output/row_189_frontmonth_substack_com_extracted.json
{
  "filename": "row_189_frontmonth_substack_com_extracted",
  "url": "https://frontmonth.substack.com/p/options-market-structure-101-b18",
  "title": "Options Market Structure 101",
  "date": "",
  "sentiment": "Neutral",
  "text": "----------------------------------------\nThis site requires JavaScript to run correctly. Please",
  "text_length": 95,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.508822",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_189_frontmonth_substack_com_extracted.txt"
  }
}

=== adam-stack-vc/606_app/results/json_output/row_106_academic_oup_com_extracted.json
{
  "filename": "row_106_academic_oup_com_extracted",
  "url": "https://academic.oup.com/rfs/article/33/4/1484/5526886",
  "title": "Back-Running: Seeking and Hiding Fundamental Information in Order Flows",
  "date": "",
  "sentiment": "Neutral",
  "text": "----------------------------------------\nWhen you visit web sites, they may store or retrieve data in your web browser. This storage is often necessary for basic functionality of the web site or the storage may be used for the purposes of marketing, analytics, and personalization of the web site such as storing your preferences.",
  "text_length": 330,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.517938",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_106_academic_oup_com_extracted.txt"
  }
}

=== adam-stack-vc/606_app/results/json_output/row_120_investing_com_extracted.json
{
  "filename": "row_120_investing_com_extracted",
  "url": "https://investing.com/news/stock-market-news/highfrequency-traders-love-business-with-robinhood-2268399",
  "title": "High-Frequency Traders Love Business With Robinhood",
  "date": "",
  "sentiment": "Neutral",
  "text": "----------------------------------------\nVerifying you are human. This may take a few seconds.\nwww.investing.com needs to review the security of your connection before proceeding.",
  "text_length": 179,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.472546",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_120_investing_com_extracted.txt"
  }
}
