=== adam-stack-vc/606_app/results/analysis_output2/conversion_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "filename": {
      "type": "string"
    },
    "url": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "date": {
      "type": "string"
    },
    "sentiment": {
      "type": "string"
    },
    "text": {
      "type": "string"
    },
    "text_length": {
      "type": "integer"
    },
    "source": {
      "type": "string"
    },
    "processing_info": {
      "type": "object",
      "properties": {
        "converted_at": {
          "type": "string"
        },
        "source_file": {
          "type": "string"
        }
      },
      "required": [
        "converted_at",
        "source_file"
      ]
    }
  },
  "required": [
    "filename",
    "url",
    "text",
    "source",
    "processing_info"
  ]
}

=== adam-stack-vc/606_app/results/json_output/row_168_investopedia_com_extracted.json
{
  "filename": "row_168_investopedia_com_extracted",
  "url": "https://investopedia.com/investing/free-stock-trading-whats-catch",
  "title": "Is There a Catch to Free Stock Trading?",
  "date": "",
  "sentiment": "Neutral",
  "text": "----------------------------------------\nInvestors can now trade stocks for free through most brokers. But how do brokerages make money if they’re waiving commissions? A deep dive into the commission-free trading movement reveals various business activities that build profits, sometimes to the disadvantage of clients. As a result, larger customers and frequent traders might want to consider paying for premium accounts.\nRobinhood pioneered commission-free trading, offering both cash and margin accounts. The broker-dealer used to advertise that it made money by earning interest on the uninvested portion of client funds.\nHowever, the return of near-zero interest rates in 2020 made that strategy far less profitable. Disclosure documents revealed other profit sources, including margin lending, monthly fees for upgraded services, and rehypothecation. Rehypothecation allowed the company to use client securities to support other financial activities.\nRehypothecation occurs in a margin account when the broker-dealer uses an asset—stock securities in this case—as collateral to fulfill their own obligations or interests. In other words, they can fund their own market bets or borrow money from a bank, using your stocks as collateral if things go haywire. This practice tends to work well in quiet times. On the other hand, it can have disastrous consequences when the financial system is under stress.\nRobinhood's new customers default to margin accounts, potentially exposing them to rehypothecation. However, customers can manually downgrade them to cash accounts.\nRobinhood also has some more conventional ways to make money. For example, the higher-tier Robinhood Gold charges a monthly fee, adding another profit source. Furthermore, they have fee schedules for all services not directly related to buying or selling stocks, such as wire transfers and overnight domestic check delivery. You’ll also pay for paper statements, transferring the account to another brokerage, and telephone assisted trades.\nPayment for order flow is a primary way that brokerages make money from commission-free trades. Payments for order flow may result in lower quality order execution, leading to slightly higher buy prices and marginally lower sell prices. This practice is by no means limited to Robinhood, and it was a growing source of revenue for brokerages in 2020. For example, TD Ameritrade received $526.59 million in payments for order flow in the second quarter of 2020.\nRobinhood itself made $271.2 million from payments for order flow during the second quarter of 2020. They told clients they're getting the best available execution price. However, Robinhood provides little detail on how they package those orders. As a result, in December 2020, the SEC charged Robinhood with violating federal securities laws, such as a lack of transparency on how the company earned revenue and failure to execute trades in the client's best interest. Robinhood had to pay $65 million in a civil penalty to the SEC.\nRobinhood is bound by Securities and Exchange Commission (SEC) Regulation NMS, which requires customers to receive the National Best Bid and Offer (NBBO). That promise may be harder to fulfill than it sounds, given the company’s terms and conditions.\nEven small delays in executing market orders can generate self-serving opportunities to adversely impact quality and build profits for the brokerage. They offer few frills and attract frequent customer service complaints, which are expected because ultrathin margins generate a natural conflict of interest between customer needs and the company's profitability. Even so, they've added features regularly in the last few years and have retained their enormous popularity. Many of these features come with price tags that add to profitability, including Robinhood Gold, which incurs monthly fees.\nMainstream brokerages, including Charles Schwab and E*Trade, also offer commission-free trading and have made substantial amounts from payment for order flow as well. Ultimately, customers of all of these brokerages must decide whether it is worth paying for better order execution.\nCommission-free stock trading evolved from a market niche dominated by Robinhood to a mainstream feature in just a few years. At the same time, adding premium and fee-based features made Robinhood more like the other brokers. However, high-volume traders still need to be careful about trade execution price and quality.",
  "text_length": 4461,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.513937",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_168_investopedia_com_extracted.txt"
  }
}

=== adam-stack-vc/606_app/results/json_output/row_035_protocol_com_extracted.json
{
  "filename": "row_035_protocol_com_extracted",
  "url": "https://protocol.com/crypto-trading-pfof-robinhood",
  "title": "Crypto has a payment for order flow problem, too",
  "date": "2/6/23",
  "sentiment": "Negative",
  "text": "----------------------------------------\nThe resource requested could not be found on this server!",
  "text_length": 98,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.504363",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_035_protocol_com_extracted.txt"
  }
}

=== adam-stack-vc/606_app/results/json_output/row_144_onlinelibrary_wiley_com_extracted.json
{
  "filename": "row_144_onlinelibrary_wiley_com_extracted",
  "url": "https://onlinelibrary.wiley.com/doi/10.1111/0022-1082.00098",
  "title": "Payments for Order Flow on Nasdaq",
  "date": "",
  "sentiment": "Neutral",
  "text": "----------------------------------------\nVerifying you are human. This may take a few seconds.\nonlinelibrary.wiley.com needs to review the security of your connection before proceeding.",
  "text_length": 185,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.509234",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_144_onlinelibrary_wiley_com_extracted.txt"
  }
}

=== adam-stack-vc/606_app/results/json_output/row_232_papers_ssrn_com_extracted.json
{
  "filename": "row_232_papers_ssrn_com_extracted",
  "url": "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=224943",
  "title": "The Allocation of Investors' Orders and Inefficient Market Competition: A Proposal",
  "date": "",
  "sentiment": "Neutral",
  "text": "----------------------------------------\nAn issue that has increasingly occupied the attention of the Securities and Exchange Commission is \"payment for order flow.\" This is the practice whereby securities markets compete for orders placed by brokers by providing side payments to brokers in return for brokers promising to send them investors' orders. Does this create inefficient nonprice competition between securities markets? The paper argues that it does, that all the proposed solutions (including the SEC's disclosure requirements) miss the mark, and that the problem is really a result of the SEC's regulation of the prices at which investors' orders must be filled. Remove this regulatory bar (with a few wrinkles) and the problem would be resolved without the need for the current cumbersome and expensive regulatory apparatus.",
  "text_length": 838,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.513391",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_232_papers_ssrn_com_extracted.txt"
  }
}

=== adam-stack-vc/606_app/results/json_output/row_158_finance_yahoo_com_extracted.json
{
  "filename": "row_158_finance_yahoo_com_extracted",
  "url": "https://finance.yahoo.com/news/gensler-zeroes-in-on-citadel-securities-as-sec-considers-payment-for-order-flow-ban-191715790.html",
  "title": "Gensler zeroes in on Citadel Securities as SEC considers payment for order flow ban",
  "date": "",
  "sentiment": "Neutral",
  "text": "----------------------------------------\nWall Street’s top cop said Tuesday that the dominance of Citadel Securities in the business of routing order flow may not be giving retail investors the best deal.\nU.S. Securities and Exchange Commission Chair Gary Gensler told the Senate Banking Committee that he’s concerned about Citadel Securities’ 47% market share over all U.S.-listed retail volume. Virtu Financial (VIRT), another wholesaler, controls about 25% to 30%.\n“I’m pro competition, and I’m not sure the payment for order flow system really is the best competitive landscape,” Gensler said.\nGensler did not mention Citadel Securities by name, but footnotes in the SEC chair’s prepared remarks did.\nThe SEC has not ruled out the possibility of a full ban on payment for order flow, the practice of a brokerage (like Robinhood) passing on stock orders to a wholesaler (like Citadel Securities) to actually locate and execute.\nWhen those wholesalers find a stock at a cheaper price than the investor ordered, the savings are split by the wholesaler and the brokerage — who can then pass on cost savings to the investor in the form of a better price. The payment for order flow model is a major reason why brokerages like Robinhood (HOOD) can offer zero commission trades.\nWholesalers also get rebates from exchanges like the New York Stock Exchange for providing liquidity, entrenching their roles as middlemen in stock trades.\n“I think the inherent conflicts of payment for order flow and rebates on the stock exchanges both may make our markets less efficient,” Gensler said.\nYahoo Finance reported that Gensler raised the issue of concentration of retail order flow in the first meeting of the White House’s Competition Council last Friday, President Joe Biden’s initiative to push federal agencies to curb anti-competitive behavior.\nQuestions remain about how the SEC will proceed on any reform.\nThe former Goldman Sachs banker alluded not only to the possibility of banning payment for order flow, but rethinking rebates and the way that prices are referenced under the benchmarks set by National Best Bid and Offer (NBBO).\n“In this area, it’s all on the table,” Gensler said, adding that the SEC’s single goal is to encourage competition “to lower the cost and raise the efficiency\" of the equity market structure.\nOnce an arcane mechanic of the brokerage industry, payment for order flow earned the national spotlight during the early 2021 frenzy over meme stocks like GameStop (GME).\nRobinhood, which went public in late July, has relied heavily on payment for order flow and saw its revenues from the practice nearly triple in 2020.",
  "text_length": 2645,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.497589",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_158_finance_yahoo_com_extracted.txt"
  }
}

=== adam-stack-vc/606_app/results/json_output/row_070_investopedia_com_extracted.json
{
  "filename": "row_070_investopedia_com_extracted",
  "url": "https://investopedia.com/robinhood-reportedly-filed-confidentially-for-ipo-5118086",
  "title": "Robinhood Reportedly Filed Confidentially for IPO",
  "date": "3/23/21",
  "sentiment": "Negative",
  "text": "----------------------------------------\nTrading app Robinhood Markets has filed confidentially for an initial public offering with the Securities and Exchange Commission (SEC).\nThe company — which has been in the spotlight as retail investors fueled a buying boom in the markets this year — decided to proceed with its IPO, though its listing plans could change, Bloomberg reported, citing people familiar with the matter. The company was reportedly valued at $12 billion in Sept. 2020, with that figure rising to about $40 billion last month.\nEarlier this year, Robinhood received negative attention after it restricted transactions for certain securities to position closing, including GameStop, AMC Entertainment, Blackberry, and Bed Bath and Beyond, among others.\nThe decision came amid extreme market volatility caused by an unprecedented volume of trading by day traders and retail investors who rallied those meme stocks to record heights. “Amid significant market volatility, it’s important as ever that we help customers stay informed,” Robinhood said at the time.\nHowever, shareholders were not happy and law firm ChapmanAlbin filed a class action lawsuit against Robinhood on behalf of users who suffered losses as a result of investing in GameStop or AMC. The lawsuit alleged that Robinhood recruited social media influencers to encourage individuals to sign up and purchase shares of GameStop and AMC, only to place trading restrictions on the securities a day later.\nThe accusation came a month after the Massachusetts attorney general claimed that Robinhood used aggressive marketing and advertising tactics like gamification to attract new, often inexperienced customers, while failing to maintain the infrastructure and procedures necessary to meet the demands of its rapidly growing customer base.\nAt the time, Robinhood denied the accusations, saying it “worked diligently to ensure our systems scale and are available when people need them.”\nRobinhood generates significant income from payments for order flow, a practice whereby a broker receives compensation and other benefits for directing orders to different parties for trade execution. Independent analysis suggests that payments for order flow generated an estimated $69 million in revenue for Robinhood in 2018, up 227% from the previous year, and accounted for more than 40% of its overall revenue. In the second quarter of 2020, Robinhood generated approximately $180 million from payments for order flow.\nOther sources of revenue include a $5 monthly fee for optional membership to Robinhood Gold, which gives the client access to margin loans and investing tools; interest on uninvested cash; lending stocks purchased on margin; and fees on purchases using the company's debit card.\nThe company has run into controversy for building its payment for order flow into its largest revenue driver. In Dec. 2020, Robinhood agreed to pay the SEC $65 million after the market watchdog charged the online brokerage for failing to disclose to customers that it received payments from trading firms for routing customer orders to them.",
  "text_length": 3108,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.475949",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_070_investopedia_com_extracted.txt"
  }
}

=== adam-stack-vc/606_app/results/json_output/row_131_sec_gov_extracted.json
{
  "filename": "row_131_sec_gov_extracted",
  "url": "https://sec.gov/newsroom/speeches-statements/gensler-volume-based-rebates-fees-101823",
  "title": "Statement on Exchanges’ Volume-Based Rebates and Fees",
  "date": "",
  "sentiment": "Neutral",
  "text": "----------------------------------------\nToday, the Commission is considering a proposal regarding exchanges’ volume-based rebates and fees. I am pleased to support this proposal because it will elicit important public feedback on how the Commission can best promote competition amongst equity market participants.\nCongress long has mandated that the SEC work to promote competition in the capital markets. In 1975, Congress amended the Exchange Act largely to address anticompetitive practices by market intermediaries. Congress added the word “competition” to the Exchange Act 20 times.[1]\nIn those 1975 provisions, Congress also mandated that exchanges’ rules “not [be] designed to permit unfair discrimination between customers, issuers, brokers, or dealers” and “provide for the equitable allocation of reasonable dues, fees, and other charges among its members.”[2]\nLater, in 1996, Congress mandated that, in addition to investor protection and public interest, the SEC consider efficiency and competition, as well as capital formation, when considering rules.[3]\nIn light of these mandates, I think it’s appropriate that the Commission make today’s proposal along with alternatives requesting public feedback on a practice the exchanges use called volume-based transaction pricing—or, what one might call volume-based discounts.\nCurrently, the playing field upon which broker-dealers compete is unlevel. Mid-sized and smaller broker-dealers effectively pay higher fees than larger brokers to trade on most exchanges. This is because exchanges generally charge brokers net trading fees or pay rebates back to brokers that vary depending on the brokers’ trading volume. As a consequence, brokers with the largest trading volume receive the largest rebates and thus pay the lowest net fees. Sometimes, large brokers get rebates that are even larger than the fees they paid—leading to a situation where the exchange actually pays on net large brokers for their order flow.\nThese larger trading firms thus are able to offer customers more favorable transaction prices than smaller brokers. Further, this has contributed to a practice whereby mid-sized or smaller brokers—in an effort to capture higher rebates—route their orders through a handful of the largest brokers. A handful of the largest brokers are then able to collect a fee for that service and use that volume to qualify for even better tiers for themselves and other customers. What’s more, some have suggested that there might be some information leakage to the largest brokers due to these routing practices.\nWe have heard from a number of market participants that volume-based transaction pricing along with these market practices raise concerns about competition in the markets.\nIn response, through today’s proposal, we request public comment regarding whether volume-based discounts should be prohibited, and if so to what degree. In addition, we request public input regarding the role that new disclosure requirements could play to address these practices.\nToday’s release offers a number of alternatives for public comment regarding both possible prohibitions and disclosure requirements.\nIn addition, today’s release includes questions about how to promote competition amongst and between trading venues as well as brokers.\nI look forward to the public’s input on these matters.\nI’d like to thank members of the SEC staff for their work on this proposal, including:\n• Haoxiang Zhu, David Saltiel, Andrea Orr, David Shillman, Eric Juzenas, Richard Holley, Terri Evans, Yvonne Fraticelli, Julia Zhang, Yue Ding, Sharon Park, and Roni Bergoffen in the Division of Trading and Markets;\n• Jessica Wachter, Jill Henderson, Oliver Richard, Paul Barton, Ariel Lohr, Sherry Wu, John Ritter, Caroline Schulte, Lauren Moore, Charles Woodworth, Parhaum Hamdi, Gregory Scopino, and Julie Marlowe in the Division of Economic and Risk Analysis;\n• Megan Barbero, Meredith Mitchell, Robert Teply, Janice Mitnick, Cynthia Ginsberg, and Ronesha Butler in the Office of the General Counsel;\n• John Polise, Connie Kiggins, Michael Hershaft, and Carrie O’Brien in the Division of Examinations;\n• Charlotte Buford and Kerry Knowles in the Division of Enforcement; and\n• Kevin Burris and David Fernandez in the Office of Legislative and Intergovernmental Affairs.",
  "text_length": 4314,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.507230",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_131_sec_gov_extracted.txt"
  }
}

=== adam-stack-vc/606_app/results/json_output/row_150_reuters_com_extracted.json
{
  "filename": "row_150_reuters_com_extracted",
  "url": "https://reuters.com/business/retail-consumer/canada-stock-market-rules-curb-platforms-linked-churning-us-stocks-2021-02-09",
  "title": "Canada stock market rules curb platforms linked to churning U.S. stocks",
  "date": "",
  "sentiment": "Neutral",
  "text": "----------------------------------------",
  "text_length": 40,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.504623",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_150_reuters_com_extracted.txt"
  }
}
