=== adam-stack-vc/606_app/results/analysis_output2/conversion_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "filename": {
      "type": "string"
    },
    "url": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "date": {
      "type": "string"
    },
    "sentiment": {
      "type": "string"
    },
    "text": {
      "type": "string"
    },
    "text_length": {
      "type": "integer"
    },
    "source": {
      "type": "string"
    },
    "processing_info": {
      "type": "object",
      "properties": {
        "converted_at": {
          "type": "string"
        },
        "source_file": {
          "type": "string"
        }
      },
      "required": [
        "converted_at",
        "source_file"
      ]
    }
  },
  "required": [
    "filename",
    "url",
    "text",
    "source",
    "processing_info"
  ]
}

=== adam-stack-vc/606_app/results/json_output/row_132_dash_harvard_edu_extracted.json
{
  "filename": "row_132_dash_harvard_edu_extracted",
  "url": "https://dash.harvard.edu/bitstreams/a9643938-23c2-4b01-a6a2-6dcca656100e/download",
  "title": "An Analysis of Payment for Order Flow in American Financial Markets",
  "date": "",
  "sentiment": "Negative",
  "text": "----------------------------------------",
  "text_length": 40,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.512189",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_132_dash_harvard_edu_extracted.txt"
  }
}

=== adam-stack-vc/606_app/results/json_output/row_107_citadelsecurities_com_extracted.json
{
  "filename": "row_107_citadelsecurities_com_extracted",
  "url": "https://citadelsecurities.com/wp-content/uploads/sites/2/2022/12/EnhancingCompetitionTransparencyandResiliencyinUSFinancialMarkets.pdf",
  "title": "Enhancing Competition, Transparency, and Resiliency in U.S. Financial Markets",
  "date": "",
  "sentiment": "Positive",
  "text": "----------------------------------------",
  "text_length": 40,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.473840",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_107_citadelsecurities_com_extracted.txt"
  }
}

=== adam-stack-vc/606_app/results/json_output/row_208_moneywise_com_extracted.json
{
  "filename": "row_208_moneywise_com_extracted",
  "url": "https://moneywise.com/investing/payment-for-order-flow",
  "title": "What is payment for order flow and why is it so controversial?",
  "date": "",
  "sentiment": "Neutral, Negative",
  "text": "----------------------------------------\nWhether you want to ride in the front seat of a crowded car or nab the last piece of cake, most of us are familiar with calling “first dibs” or similar to get the first opportunity at something before anyone else.\nWhat is payment for order flow (PFOF)?\nPayment for order flow (PFOF) refers to a practice where a stock broker receives compensation for routing an order to a particular market maker. In other words, it means your broker is getting paid to process your trades though a certain third party.\nWhen you normally place a trade, your broker works with a clearing fim to route the order. This ensures that your order is actually processed properly and the correct trading info flows between broker, market maker, and the exchange.\nThis can be a complex concept to understand, so here’s an example:\nLet’s say you want to sell 100 shares of Stock X, so you log into your brokerage or stock trading app and enter an order to sell 100 shares. If your brokerage participates in PFOF, the sale may not go right to the New York Stock Exchange or Nasdaq. Instead, a middleman company will quickly analyze the transaction to decide if it can profit from the order by managing the trade on its own.\nIf someone else out there wants to buy 100 shares of Stock X and their brokerage uses the same middleman for order flow, the company in the middle could intercept the trade, route the trade on its own and capture a small profit. This order never goes through a major stock exchange. The middle company shares a portion of that profit with the participating brokerages that put your trade into their system.\nAs you can probably tell, this present a potential conflict of interest. This is because with PFOF, your broker is receiving compensation for routing your order to a specific market maker, which might not always be in your best interest.\nPayment for order flow traces its roots to an infamous name in investing: Bernie Madoff. Madoff pioneered this system as a way for large market makers to profit from trade activity. At one point, Madoff’s firm was paying to take about 10% of volume from the New York Stock Exchange. That’s massive — and the influence of just one firm.\nToday, major firms including Citadel Securities and Virtu Americas are big players in the PFOF business. When brokerages stopped charging high commissions for executing trades, payment for order flow became a lucrative option to make up for lost revenue.\nPayment for order flow takes place at many “free” and discount brokerages. Because of controversies surrounding the practice, some brokerages like Public, don’t participate in this. Others, like Robinhood, rely on this practice as a major part of their business model.\nHow does payment for order flow work?\nLet’s dig in deeper to how payment for order flow works so you can understand where the money goes, how it impacts you and why it’s lucrative for investment firms.\nAs an example, imagine you want to sell 100 shares of Starbucks and the current market price is $100 per share. You grab your phone, tap a few buttons and enter a market order to sell your shares.\nRather than go right to the NASDAQ to execute the trade, it’s intercepted by Citadel, a major pay for order flow firm. At the same moment you enter your trade, the market price moves to $99.99 per share and someone else enters a limit order to buy 100 shares at $100.01 per share.\nCitadel notices this seconds-long discrepancy in the market. It sends your trade to fulfill the limit order at $100.01 per share and fulfills your order at the market price of $99.99. That’s a two-cent spread per share worth $2 total for this trade. Citadel keeps the $2 and sends part to your brokerage as payment for order flow.\nDepending on your brokerage’s timing, you may also see a small price improvement on your order so you get a small bit of the profit. However, the CFA Institute equates this to paying a dollar to get a penny back. Generally, payment for order flow is a completely invisible process that could happen to almost all of your stock orders without your knowledge.\nFurther reading: How to protect your investments\nThe $2 profit in the section above doesn’t sound like a lot, but imagine that the same process happens several million or billion times per day. All of a sudden, that pile of $2 here and $0.20 there turns into millions or billions of dollars to be split up between payment for order flow firms and participating brokerages that send trades.\nIf you watched Superman 3 or Office Space, you know that fractions of a penny can add up to a high income over time. With PFOF, high-frequency trading firms and brokerages all play in a system that divvies up fractions of a cent for business profits. But when someone is winning by taking advantage of high-speed trading and payment for order flow, someone else is stuck paying the bill.\nWhy is payment for order flow controversial?\nThe big controversy around this practice comes from retail consumers like you and me. In the example above with Starbucks stock, the two individual traders buying and selling 100 shares are the losers who wind up giving away $2 that one of them should have arguably been able to keep.\nInstead, that $2 is split up between the brokerage and payment for order flow firm. And most consumers have no idea this is happening. So while investment apps like Robinhood and various full-service brokers may appear to be “free” on the surface, you may be paying in another way that doesn’t involve traditional commission.\nThe SEC requires brokers to disclose that they use payment for order flow when you open an account. Brokers must also send reports regarding their net payments from market makers and the rate of payment for order flow. And in some cases, brokers get a slap on the wrist for not disclosing this revenue source clearly enough, like when the SEC fined Robinhood $65 million. But for the most part, everyday investors don't really know or notice how much money they lose to this business practice.\nBecause of this potential to exploit the little guy, countries such as Canada have completely banned payment for order flow while others are reviewing the practice. While market makers have some rules and regulations that require them to give traders a reasonable deal based on real market rates, there is plenty of room to earn slivers of a profit by taking advantage of unaware individual investors.\nHow to avoid payment for order flow\nIf you sign up for a brokerage firm that offers commission-free trading,\nthere’s a good chance your orders are subject to payment for order flow.\nThe only way to avoid this practice is to pick a brokerage that doesn’t participate or gives you the option to opt out.\nPublic is one of the more popular investing apps that relies on tips to make money instead of payment for order flow. This is one reason people often choose Public over Robinhood or other similar trading apps.\nOf course, it could be worth paying a small amount, even with this practice, to enjoy the best brokerage experience for your needs. If one brokerage offers an amazing service and requires this practice, it could still be a better choice than a brokerage that doesn’t use PFOF but provides sub-standard tools and resources.\nIf you are set against getting caught up in payment for order flow, read the fine print on your brokerage website and any other broker you’re considering. The practice is widespread, and you may have to do a little legwork to find a brokerage that sends every order directly to the market.\nThis practice is a good idea for the brokerages and trading firms that profit from the practice. And some investors argue that smaller brokers can provide better service to customers by routing excess orders to market makers to make things running smoothly. And, theoretically, brokers could pass on some of their PFOF profits to customers with lower fees and perks.\nHowever, for most individual investors, it isn’t a good thing. Payment for order flow introduces conflicts of interest that ultimately have the potential to cost you money. And the worst part is that these fees are hard to detect, even though the SEC requires brokers to disclose their policies surrounding payment for order flow practices.\nBut because it’s so common and tough to avoid, you may be stuck with it while regulators and firms duke out the details.",
  "text_length": 8394,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.506152",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_208_moneywise_com_extracted.txt"
  }
}

=== adam-stack-vc/606_app/results/json_output/row_125_edition_cnn_com_extracted.json
{
  "filename": "row_125_edition_cnn_com_extracted",
  "url": "https://edition.cnn.com/2022/12/15/investing/sec-payment-for-order-flow",
  "title": "Massive changes could be coming to the way the stock market functions",
  "date": "",
  "sentiment": "Positive, Negative",
  "text": "----------------------------------------\nWall Street’s top cop has voted in favor of major changes to the way millions of everyday investors buy and sell stocks.\nThe Securities and Exchange Commission Wednesday proposed a rule that it says would add competition to an unseen — but potentially costly — part of the stock trading system for retail investors. The changes won’t be implemented just yet — a vote in the spring could finalize the rules. But the agency is majority controlled by Democrats and the proposal is expected to be adopted next year.\nToday, when you buy or sell a stock on an app, the trade appears to be instantaneous. But beneath that simple buy/sell action is a complex web of Wall Street players exploiting tiny differences in price to rake in huge amounts of cash.\nWhen you tap buy or sell, the broker, such as Robinhood or E*Trade, takes your order to a firm known as a wholesaler or market maker — middlemen firms that are supposed to get you the best price. Wholesalers pay the brokers for the privilege of executing the trades.\nThat process is known as “payment for order flow.” To support free trading, brokers typically make pennies from wholesalers off each transaction — but those pennies add up, accounting for the bulk of brokerages’ revenues. The SEC said the six largest wholesalers collectively paid retail brokers $235 million in payment for order flow for stock orders in the first quarter of 2022.\nPayment for order flow has come under intense scrutiny by regulators following the fallout from the January 2021 run-up in meme stocks like GameStop. The SEC notes that wholesalers typically execute trades “without providing any opportunity for other market participants to compete to provide a better price.”\nThe SEC’s proposed changes would add more competition at the middleman level to ensure retail investors are actually getting the best prices. Orders would be routed into auctions where trading firms would have to compete to execute them.\nSEC Chair Gary Gensler has been a longtime critic of the way the current payment for order flow market operates, arguing that it lacks transparency and competition to the detriment of investors.\nGensler and other critics of the process say the brokers and market makers have conflicts of interest, and that payment for order flow hurts everyday investors while amassing huge wealth for Wall Street firms.\n“Today’s markets are not as fair and competitive as possible for individual investors — everyday retail investors,” Gensler said. “This is in part because there isn’t a level playing field among different parts of the market: wholesalers, dark pools, and lit exchanges.”\nGensler noted that everyday folks don’t have the same benefits as larger, deeper-pocketed investors who are often able to execute orders at the best price possible.\n“The markets have become increasingly hidden from view, especially for individual investors,” Gensler said. “Thus, today’s proposal is designed to bring greater competition in the marketplace for retail market orders.”",
  "text_length": 3045,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.509496",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_125_edition_cnn_com_extracted.txt"
  }
}

=== adam-stack-vc/606_app/results/json_output/row_025_protocol_com_extracted.json
{
  "filename": "row_025_protocol_com_extracted",
  "url": "https://protocol.com/fintech/stock-trading-parkside",
  "title": "Robinhood made stock-trading an app sensation. Parkside Securities wants to take the action global.",
  "date": "2/6/23",
  "sentiment": "Positive",
  "text": "----------------------------------------\nThe resource requested could not be found on this server!",
  "text_length": 98,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.514938",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_025_protocol_com_extracted.txt"
  }
}

=== adam-stack-vc/606_app/results/json_output/row_046_webullapp_com_extracted.json
{
  "filename": "row_046_webullapp_com_extracted",
  "url": "https://webullapp.com/news-detail/51113885",
  "title": "SEC Chair Gensler Could Restrict Payment For Order Flow This Week: What Investors Need To Know",
  "date": "7/6/22",
  "sentiment": "Neutral",
  "text": "----------------------------------------\nSEC Chair Gensler Could Restrict Payment For Order Flow This Week: What Investors Need To Know\nGameStop Corp. (NYSE: GME) and AMC Entertainment Holdings Inc (NYSE: AMC) traders at the epicenter of the meme stock trading frenzy in 2021 could get a big update this week on the way brokers like Robinhood Markets In\nGameStop Corp. (NYSE:GME) and AMC Entertainment Holdings Inc (NYSE:AMC) traders at the epicenter of the meme stock trading frenzy in 2021 could get a big update this week on the way brokers like Robinhood Markets Inc (NASDAQ:HOOD) are allowed to run their businesses.\nOn Wednesday, U.S. Securities and Exchange Commission Chair Gary Gensler is speaking at the Piper Sandler Global Exchange and Fintech Conference at 12 p.m. ET. Gensler is expected to detail plans to overhaul the way retail investors' orders are routed, according to the Wall Street Journal.\nRelated Link: After Huge Sell-Offs, Have Robinhood And Peloton Become Buyout Targets?\nWhat Is Payment For Order Flow? Under the current market rules, brokers like Robinhood and Charles Schwab Corporation (NYSE:SCHW) are required to perform \"reasonable diligence\" to determine the best way to route a so-called market order in which the retail trader does not specify a minimum or maximum price for the trade.\nThrough a process called payment for order flow, or PFOF, Robinhood and other brokers receive compensation for routing their orders to specific wholesalers. These wholesalers include Citadel Securities and Virtu Financial Inc (NASDAQ:VIRT).\n“Off-exchange market makers make payments to retail brokers for the privilege of having their customer's orders routed to them first. The market maker will execute directly against the retail order [if they think they can make money from it]. They are basically paying for the privilege of having ‘first dibs’ to trade against the ‘dumb money,'” Benzinga's Premarket Prep co-host Dennis Dick recently said.\nThe End Of PFOF? More than 70% of Robinhood's total revenue in the first quarter of 2022 came from PFOF, which some investors, and even Gensler himself, see as a conflict of interest.\nGameStop and AMC traders accused Citadel Securities of pressuring Robinhood to place trading halts and restrictions on meme stocks in early 2021, although both parties involved deny any such communication took place.\nOn Wednesday, Gensler is expected to detail a new auction process through which firms would bid against each other to win retail traders' order flows.\nIf that change is enacted, it could mean retail investors will be getting better prices on their trades in the near future. It could also mean brokerages like Robinhood will be forced to go back to charging trading commissions if they lose their primary source of revenue.\nBenzinga's Take: PFOF is akin to a hidden trading fee. Rather than the old model of charging traders a flat, upfront fee for each trade, online brokers are now simply selling their order flow to market makers, potentially resulting in lower selling prices and higher purchase prices for their users.",
  "text_length": 3094,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.505094",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_046_webullapp_com_extracted.txt"
  }
}

=== adam-stack-vc/606_app/results/json_output/row_082_tradersmagazine_com_extracted.json
{
  "filename": "row_082_tradersmagazine_com_extracted",
  "url": "https://tradersmagazine.com/am/the-hidden-costs-of-robinhood",
  "title": "The Hidden Costs of Robinhood",
  "date": "9/8/20",
  "sentiment": "Negative",
  "text": "----------------------------------------\nI’ve got to hand it to the upstart brokerage “disrupter” Robinhood. They have been remarkably consistent in their message from day one. In October of 2018, co-founder Vlad Tenev put it this way:\nWe’ve grown to over six million customers in under four years by offering our services at a dramatically lower cost and better experience than others.\nMr. Tenev’s comment came in the context of a founder blog post where he felt the need to explain to his users, and to the world, why it’s so good for Robinhood’s users that Robinhood generates revenues by selling their user’s orders to market makers – a practice known as payment for order flow or simply PFOF.\nThe language to describe the good intentions of Robinhood and the myriad benefits to Robinhood’s users is a marvel. The double-speak in these platitudes is stunning – even by today’s low standards. Let me highlight a few gems.\n“When you buy or sell stocks on Robinhood, like many other brokerages, we send your order to market makers like Two Sigma, Citadel [Securities], and Virtu, instead of exchanges like NYSE. Market makers don’t front-run your orders — they’re actually required by Regulation NMS to execute your order at the best price among all of the exchanges, and unlike exchanges, they don’t charge fees.”\nOK. Great. This statement implies that the other alternatives to market makers, like maybe the NYSE, DO front-run your orders. This is a not-so-subtle implication that it is in fact the stock exchanges that will front-run your orders since Mr. Tenev is contrasting the choice to send your orders to market makers instead of sending them to the NYSE. Last I checked, front-running stocks was illegal everywhere. If Mr. Tenev has evidence of front-running stocks at the NYSE, I would hope that he would share it with the SEC. He certainly has a duty to do so if the NYSE is indeed front-running its customers. More than likely, however, he is just using the NYSE as a false-dilemma to defend his firm’s choice to use PFOF as the major source of Robinhood’s revenues.\n“We send your orders to the market maker that’s most likely to give you the best execution quality. For even finer control, we offer limit orders and stop limits, which allow you to name your own price.”\nWell, just twelve months after Mr. Tenev penned his post, Robinhood was fined $1.25M by its regulator FINRA for “best-execution violations.” According to Business Insider, “Robinhood also did not perform regular best-execution reviews on several order types, including limit trades, stop orders, and after-hours trades, the regulator added.”\n“Our goal is to build the world’s most customer-centric financial company.”\nBy any reasonable definition a company’s customers are the other people and businesses that pay the company money. Recent changes in regulatory disclosure requirements for broker-dealers revealed that Robinhood derived fully 70% of its revenues in 1Q 2020 from – you guessed it – market makers.\nRobinhood’s users are not Robinhood’s customers. This should not come as a surprise since Robinhood is backed by the same west coast VC technology firms that brought us Google, Facebook and other luminaries of what Harvard Professor Shoshanna Zuboff has correctly identified as “surveillance-capitalism.” Surveillance capitalism offers “free” services to users and it then bundles the collective behaviors of its users and sells predictions of those ensemble behaviors to the highest bidders. Google’s customers are Google’s advertisers, not those of us who use Google to search the internet. Robinhood’s customers are the market makers, not those using Robinhood’s tools to execute trades.\n“For you, this means even more products with a spectacular customer experience and the lowest possible prices.”\nDo investors and traders really need “more products with a spectacular customer experience and the lowest possible prices”? Is this what is going to finally lead the retail investor to the promised land of at least holding their own against institutional investors rather than chronically underperforming the market averages? Are free-trades the magic missing ingredient that explains the chronic underperformance of the retail investor who tries his or her own hand in the stock market?\nThe assertion that free trades and a “spectacular customer experience” will give Robinhood’s users a decisive edge is so naïve that it can only be read as a disingenuous sleight-of-hand. Anyone with even a couple of years of experience as an investor can tell you that it’s not commission costs which undermine retail investors. And besides, what does a “spectacular customer experience” even mean? If we are to judge by the standards of Robinhood’s Silicon Valley tech peers, it means an experience that is gamified and addictive. Isn’t it rather convenient to be able to apply such technology to one of the most potentially addictive activities of all time – stock market speculation?\nRetail investors are undermined by their behaviors – not their tools and their commissions. Successful investing and trading is first and foremost a matter of having a viable plan and executing that plan consistently over an extended period of time.\nRobinhood users do have a plan and they are consistent. The trouble is that their plans are not plans of their own making and their consistent behaviors are not behaviors that lead to long-term success.\nPer 2Q 2020 regulatory filings, Robinhood generated $111M from market makers for driving its customers into options trades. Robinhood earned $0.58 per options trade versus just $0.17 per trade for an equity trade. Making it easy for novice investors to trade options must be part of the “spectacular customer experience” that Mr. Tenev foresaw for his “customers.”\nDoes anyone think that there might be some hidden costs in novice investors executing complicated options strategies that could possibly offset the benefits of those options trades being “free”?\nLet’s see … so Robinhood is bringing a bunch of novice participants into the markets and providing a “spectacular customer experience” to trade options for free and they are earning hundreds of millions of dollars from market makers in return for delivering order flow.\nMaybe it’s the NYSE that should consider reporting Robinhood to the SEC.\nOh, wait a minute, the SEC just announced that once again, it is Robinhood that is being investigated for misleading its customers about its payment for order flow practices. This time the fines being discussed have gone up by an order of magnitude to over $10M versus the mere $1.25M they were fined less than a year ago.\nI wonder when the SEC is going to get around to investigating the NYSE for the “front-running” that Mr. Tenev and Robinhood’s market maker customers find so troubling.\n“Spectacular” is a word that comes to mind.\nDr. Richard Smith, Berkeley Mathematician and PhD in System Science, is a fintech entrepreneur and the CEO of The Foundation of the Study of Cycles. Dr. Smith has built a reputation as “The Doctor of Uncertainty” amongst his academic peers and has helped government agencies and Fortune 500 companies (including Pfizer and Johnson & Johnson) alike make sense of complex sets of data. With his background in mathematical theories of uncertainty combined with his investing and trading experience, Dr. Smith is an expert in risk management with critical insights that can help empower investors of all levels. Some of Dr. Smith’s findings are stunning – like empirical data-driven proof that even the world’s best investors, from Warren Buffett to Carl Icahn to David Einhorn and many more, could see their results significantly improved through the use of technology that helps course-correct irrational tendencies and cognitive biases. Dr. Smith’s software, backed by proprietary algorithms and Nobel prize winning research, has served more than 25,000 investors and helps steward more than $20 billion in assets. Dr. Smith is a regular speaker and lecturer and particularly enjoys opportunities to share his knowledge and help others gain an edge in the market.",
  "text_length": 8129,
  "source": "html_extractor",
  "processing_info": {
    "converted_at": "2025-10-02T17:16:35.472721",
    "source_file": "/Users/adamsussman/Documents/606_app/extracted_content/row_082_tradersmagazine_com_extracted.txt"
  }
}
